name: NametagEdit
main: ru.warmine.minigames.NametagEdit
version: 4.5.1
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]
