name: NametagEdit
main: ru.warmine.minigames.NametagEdit
version: ${project.version}
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]
